# Generated by Django 2.2.10 on 2020-02-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-releaseTime']},
        ),
    ]
