# Generated by Django 2.2.10 on 2020-02-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200219_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pictrueUrl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
