# Generated by Django 2.2.10 on 2020-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_pictrueurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reportSource',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
