version: '3'
services:
  db:
    image: postgres
  2091ncov:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate
    ports:
      - "8000:8000"
    depends_on:
      - db