# Generated by Django 2.2.10 on 2020-02-20 07:58

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("peopleapp", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="TotalEpidemic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epidemics", jsonfield.fields.JSONField(default=dict)),
                (
                    "crawled_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="crawled datetime",
                    ),
                ),
            ],
            options={"ordering": ["-crawled_at"]},
        )
    ]
