# Generated by Django 2.2.10 on 2020-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemic', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='epidemic',
            constraint=models.UniqueConstraint(fields=('name', 'published_at'), name='unique_name'),
        ),
    ]
